DTSPO-5507 - add smoke tests
hmcts/labs-louisehuyton-nodejs pull request #8
Opened 2022-01-27 13:52 UTC by louisehuyton

### JIRA link (if applicable) ###
DTSPO-5507

### Change description ###
Added smoke tests

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[X] No
```

2022-01-28 10:12 UTC, msl8r approved these changes

2022-01-28 10:13 UTC, timja requested changes

2022-01-28 10:13 UTC, timja commented on src/test/smoke/smoke.ts
> +
```suggestion
const testUrl = process.env.TEST_URL || 'https://localhost:8080'
```

2022-01-28 10:13 UTC, timja commented on src/test/smoke/smoke.ts
> +];
remove this

2022-01-28 10:13 UTC, timja commented on src/test/smoke/smoke.ts
> +  describe('Health Check', () => {
remove this health check test it's meaningless

2022-01-28 10:13 UTC, timja commented on src/test/smoke/smoke.ts
> +  { name: 'Default Page Template', url: 'http://localhost:8080', heading: '<h1 class="govuk-heading-xl">Default page template</h1>', },
best just to inline this and remove the .each, i.e. just check the home page

2022-01-28 10:13 UTC, timja commented on src/test/smoke/smoke.ts
> +          const response: AxiosResponse = await axios.get(url, {
```suggestion
          const response: AxiosResponse = await axios.get(testUrl, {
```

2022-01-28 15:24 UTC, timja reviewed
something like this

2022-01-28 15:24 UTC, timja commented on src/test/smoke/smoke.ts
> +jest.setTimeout(15000);
I would start without this
```suggestion
```

2022-01-28 15:24 UTC, timja commented on src/test/smoke/smoke.ts
> +  });
can you remove this please, we shouldn't be testing htis
```suggestion
```

2022-01-28 15:24 UTC, timja commented on src/test/smoke/smoke.ts
> +  describe('UI Test', () => {
```suggestion
  describe('Home page loads with correct content', () => {
```

2022-01-28 15:24 UTC, timja commented on src/test/smoke/smoke.ts
> +    describe('Required services should have a heading present with the correct text displayed', () => {
```suggestion
```

2022-01-28 15:24 UTC, timja commented on src/test/smoke/smoke.ts
> +      test(`${testUrl}`, async () => { // eslint-disable-line @typescript-eslint/no-empty-function
```suggestion
      test('with correct content', async () => {
```

2022-01-28 15:24 UTC, timja commented on src/test/smoke/smoke.ts
> +            throw new Error(` Heading not present and/or correct`)
```suggestion
            throw new Error('Heading not present and/or correct')
```

2022-01-28 16:13 UTC, timja commented on src/test/smoke/smoke.ts
> +  describe('Home page loads with correct content', () => {
```suggestion
  describe('Home page loads', () => {
```

2022-01-28 16:13 UTC, timja approved these changes
if it passes

2022-02-03 16:27 UTC, timja commented on Jenkinsfile_CNP
> +  }
you shouldn't be adding these, the app should be configured to output to the right location

2022-02-04 10:36 UTC, merged